name: Build and Push Docker Images

on:
  # Execute this workflow automatically when workflow is completed
  workflow_run:
    workflows: ["Provision Infrastructure"] # Name of the job
    types:
      - completed
  
  workflow_dispatch: # Allowance to execute it manually

permissions:
  contents: read
  security-events: write

env:
  RG_GROUP_NAME: 'azurestore-rg'
  APP_SERVICE_NAME: 'azurestore-app'
  ACR_NAME: 'azurestoreacr'
  PETSTOREPETSERVICE_IMAGE: 'petstorepetservice'
  PETSTOREPRODUCTSERVICE_IMAGE: 'petstoreproductservice'
  PETSTOREORDERSERVICE_IMAGE: 'petstoreorderservice'
  PETSTOREAPP_IMAGE: 'petstoreapp'

jobs:
  build-and-push:
    name: Compile Docker Images and Push to ACR
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Checkout the branch used for the previous Workflow
      - name: Checkout branch from triggering workflow
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref_name }}

      # Dynamic authentication on Azure and Login in ACR
      - name: Dynamic ACR Authentication via Azure CLI
        env:
          ARM_CLIENT_ID: ${{ vars.TF_VAR_AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.TF_VAR_AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          az login --service-principal -u "${ARM_CLIENT_ID}" -p "${ARM_CLIENT_SECRET}" --tenant "${ARM_TENANT_ID}"
          
          ACR_ADMIN_PASSWORD=$(az acr credential show --name ${{ env.ACR_NAME }} --query "passwords[0].value" -o tsv)
          
          mkdir -p ~/.docker
          echo '{"auths":{}}' > ~/.docker/config.json
          
          echo "$ACR_ADMIN_PASSWORD" | docker login ${{ env.ACR_NAME }}.azurecr.io -u ${{ env.ACR_NAME }} --password-stdin

      # --- PET SERVICE ---
      - name: Build Pet Store Pet Service Docker Image
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.PETSTOREPETSERVICE_IMAGE }}:${{ github.sha }} \
                       -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.PETSTOREPETSERVICE_IMAGE }}:latest ./app/petstorepetservice
      
      # Security Scan with Trivy
      - name: Trivy Pet Store Pet Service Container Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.ACR_NAME }}.azurecr.io/${{ env.PETSTOREPETSERVICE_IMAGE }}:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-image-results.sarif'
          exit-code: '0'
          severity: 'HIGH,CRITICAL'

      # --- PRODUCT SERVICE ---
      - name: Build Pet Store Product Service Docker Image
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.PETSTOREPRODUCTSERVICE_IMAGE }}:${{ github.sha }} \
                       -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.PETSTOREPRODUCTSERVICE_IMAGE }}:latest ./app/petstoreproductservice
      
      - name: Trivy Pet Store Product Service Container Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.ACR_NAME }}.azurecr.io/${{ env.PETSTOREPRODUCTSERVICE_IMAGE }}:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-image-results.sarif'
          exit-code: '0'
          severity: 'HIGH,CRITICAL'
      
      # --- ORDER SERVICE ---
      - name: Build Pet Store Order Service Docker Image
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.PETSTOREORDERSERVICE_IMAGE }}:${{ github.sha }} \
                       -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.PETSTOREORDERSERVICE_IMAGE }}:latest ./app/petstoreorderservice
      
      - name: Trivy Pet Store Order Service Container Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.ACR_NAME }}.azurecr.io/${{ env.PETSTOREORDERSERVICE_IMAGE }}:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-image-results.sarif'
          exit-code: '0'
          severity: 'HIGH,CRITICAL'

      # --- APP FRONTEND ---
      - name: Build Pet Store App Docker Image
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.PETSTOREAPP_IMAGE }}:${{ github.sha }} \
                       -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.PETSTOREAPP_IMAGE }}:latest ./app/petstoreapp
      
      - name: Trivy Pet Store App Container Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.ACR_NAME }}.azurecr.io/${{ env.PETSTOREAPP_IMAGE }}:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-image-results.sarif'
          exit-code: '0'
          severity: 'HIGH,CRITICAL'

      # Publish security report
      - name: Upload Trivy scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'trivy-image-results.sarif'

      # Push images to the Azure Container Registry
      - name: Push Docker Images to ACR
        run: |
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.PETSTOREPETSERVICE_IMAGE }}:${{ github.sha }}
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.PETSTOREPETSERVICE_IMAGE }}:latest

          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.PETSTOREPRODUCTSERVICE_IMAGE }}:${{ github.sha }}
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.PETSTOREPRODUCTSERVICE_IMAGE }}:latest

          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.PETSTOREORDERSERVICE_IMAGE }}:${{ github.sha }}
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.PETSTOREORDERSERVICE_IMAGE }}:latest

          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.PETSTOREAPP_IMAGE }}:${{ github.sha }}
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.PETSTOREAPP_IMAGE }}:latest

      # Automatic deployment of the imagen in the Azure App Service
      - name: Deploy Container to Azure App Service
        env:
          ARM_CLIENT_ID: ${{ vars.TF_VAR_AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          # Login into Azure CLI
          az login --service-principal -u "${ARM_CLIENT_ID}" -p "${ARM_CLIENT_SECRET}" --tenant "${ARM_TENANT_ID}"
          
          # Configure the images and credentials in the App Service automatically
          az webapp config container set \
            --name "${{ env.APP_SERVICE_NAME }}"" \
            --resource-group "${{ env.RG_GROUP_NAME }}" \
            --container-image-name "${{ env.ACR_NAME }}.azurecr.io/${{ env.PETSTOREAPP_IMAGE }}:${{ github.sha }}" \
            --container-registry-url "https://${{ env.ACR_NAME }}.azurecr.io" \
            --container-registry-user "${{ env.ACR_NAME }}" \
            --container-registry-password "$(az acr credential show --name ${{ env.ACR_NAME }} --query 'passwords[0].value' -o tsv)"